---
java_version: "LATEST"
java_jvm: jre-8u251-linux-x64.tar.gz
sdkman_update_alternatives:
  - candidate: java
    name: java
    link: /usr/bin/java
  - candidate: java
    name: javac
    link: /usr/bin/javac
  - candidate: java
    name: javadoc
    link: /usr/bin/javadoc
