---
-
  name: "Installing gradle {{ gradle_version }}"
  ansible.builtin.shell: "{{ item }}"
  become: true
  become_user: "{{ service_user }}"
  args:
    executable: "/bin/bash"
    creates: "{{ service_home_dir }}/.sdkman/candidates/gradle/current/bin/gradle"
  with_items:
    - "source {{ service_home_dir }}/.sdkman/bin/sdkman-init.sh && sdk install gradle {{ gradle_version }} && sdk default gradle {{ gradle_version }}"

-
  name: "Adding Gradle to /etc/profile.d/gradle.sh for {{ service_user }}"
  ansible.builtin.lineinfile:
    mode: '0755'
    path: "{{ item.dir }}"
    regexp: "^PATH=\"$PATH:{{ service_home_dir }}/.sdkman/candidates/gradle/current/bin\""
    insertbefore: EOF
    create: true
    line: 'PATH=$PATH:{{ service_home_dir }}/.sdkman/candidates/gradle/current/bin'
  with_items:
    - { user: "{{ service_user }}", dir: "/etc/profile.d/gradle.sh" }

-
  name: "Updating alternatives for Gradle"
  community.general.alternatives:
    name: "{{ item.name }}"
    path: "{{ sdkman_dir }}/candidates/{{ item.candidate }}/current/bin/{{ item.name }}"
    link: "{{ item.link }}"
  loop: "{{ sdkman_update_alternatives }}"
  become: true
  when: ansible_os_family != 'Darwin'
  tags:
    - sdkman_privilege
