---
domino_user: domino
domino_group: domino
domino_home_dir: /local/notesdata
domino_user_soft_limit: "60000"
domino_user_hard_limit: "80000"
kyr_cert: keyfile.kyr
id_vault_name: DemoVault
id_vault_password: IDVaultPassword
id_vault_help_text: Please create an issue in the DominoVagrant Issues Page for help!
domino_admin_user_first_name: Demo
domino_admin_user_last_name: Admin
domino_admin_user_id: demo-user.id
domino_admin_notes_id_password: "password"
domino_dev_user_first_name: Dev
domino_dev_user_last_name: User
domino_dev_user_short_name: DevUser
domino_dev_user_id: dev-user.id
domino_dev_user_id_password: "password"
domino_major_version: "12"
domino_minor_version: "0"
domino_patch_version: "2"
domino_server_installer_tar: "Domino_12.0.2_Linux_English.tar"
domino_notesini_servertasks: "HTTP,nomad"
domino_installer_fixpack_install: false
domino_fixpack_version: FP1
domino_server_fixpack_tar: "Domino_1202FP1_Linux.tar"
domino_installer_hotfix_install: false
domino_hotfix_version: HF50
domino_server_hotfix_tar: "1201HF50-linux64.tar"
domino_installer_base_url: "https://mydomain.com"
domino_installer_url_user: "SomeHTTPUser@mydomain.com"
domino_install_dir: /opt/hcl/domino/notes/latest/linux
domino_install_basedir: /opt/hcl/domino
domino_https_enabled: 1
domino_server_clustermates: 0
domino_organization: STARTcloud
domino_countrycode: null
domino_install_port_forwards:
  -
    guest: 442
    url: "domino"
  -
    guest: 82
    url: "domino"
  -
    guest: 1352
    url: "domino"
domino_install_proxy_url: "{{ domino_install_port_forwards[0].url }}.{{ settings.hostname }}.{{ settings.domain }}"
