---
run_tasks: true
package_arch:
  - arm64
  - amd64
package_name: startcloud
package_version: 0.0.1
package_maintainer_email: "{{ email }} | default('support@startcloud.com')"
package_dependencies:
  - libc6
package_maintainer_address: "https://www.startcloud.com"
package_description: "Package to Manage and Monitor STARTcloud instances"