---
extra_packages:
  - htop
packages:
  - htop
  - lynx
  - lshw
  - libxml2-utils
  - tree
  - python3-pexpect
  - python3-pymongo
  - python3-pymysql
  - psutils
  - python3-psutil
  - libxml2-utils

extra_repos:
  - name: "startcloud"
    gpg_key_url: "https://public.debian.packages.startcloud.com/debian/startcloud-archive-keyring.asc"
    gpg_keyring_path: "/etc/apt/keyrings/startcloud-archive-keyring.gpg"
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/startcloud-archive-keyring.gpg] https://public.debian.packages.startcloud.com/debian/ {{ ansible_distribution_release }} main"
    needs_dearmor: true
