---
run_tasks: true
count_progress: true
progress_units: 1
progress_role_description: "Securing Server"

show_help: true
lockdown_user_private_key_path: /home/startcloud/.ssh/id_ssh_rsa
lockdown_use_settings_password: false
lockdown_new_password: "STARTcloud24@!"
lockdown:
  - exim4
  - portmap
  - rpcbind.target
  - rpcbind.service
  - rpcbind.socket
  - nfs-kernel-server

# List of files/paths to be cleaned up by the lockdown role.
# Other roles can append to this list.
lockdown_file_cleanups_list: []
