---
run_tasks: true
# Import domino_oidc_debug from domino_oidc role if not defined
domino_oidc_debug: "{{ domino_oidc_debug | default(false) }}"
leap_version: 1.1.6

# HCL Domino Leap archive naming pattern: hcl.dleap-[version].[build].zip
# Mapping of versions to their corresponding build numbers
leap_build_map:
  "1.1.0": "15"
  "1.1.1": "18"
  "1.1.5": "4"
  "1.1.6": "25"
  "1.1.7": "29"
  "1.1.8": "25"
  "1.1.9": "36"


# Archive determined by set_fact in tasks/main.yml

leap_debug: false
installer_url_app_path: "SHI/Leap"
domino_leap_port_forwards:
  -
    guest: "{{ domino_install_port_forwards[0].guest }}"
    url: "leap"
  -
    guest: "{{ domino_install_port_forwards[1].guest }}"
    url: "leap"
domino_leap_proxy_url: "{{ domino_leap_port_forwards[0].url }}.{{ settings.hostname }}.{{ settings.domain }}"
domino_oidc_provider_leap_home_url: "/volt-apps/secure/org/ide/manager.html"
domino_leap_inet_site_create: true
