---
run_tasks: true
maven_version: 3.6.3

sdkman_update_alternatives:
  - candidate: maven
    name: mvn
    link: /usr/bin/mvn

# Progress reporting
count_progress: true
progress_units: 1
progress_role_description: "Configuring Maven via SDKMAN"
