---
leap_archive: Leap-1.0.5.zip
leap_version: 1.0.5
leap_debug: false
domino_leap_port_forwards:
  -
    guest: "{{ domino_install_port_forwards[0].guest }}"
    url: "leap"
  -
    guest: "{{ domino_install_port_forwards[1].guest }}"
    url: "leap"
domino_leap_proxy_url: "{{ domino_leap_port_forwards[0].url }}.{{ settings.hostname }}.{{ settings.domain }}"
