---
run_tasks: true
count_progress: true
progress_units: 1
progress_role_description: "Configuring BGinfo"

# BGInfo URLs
bginfo_config_url: "https://www.m4kr.net/downloads/{{ vendor | default('STARTcloud') }}.bgi"

# BGInfo directories
bginfo_directory: "C:\\opt\\STARTcloud\\backgrounds"
startup_directory: "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
